version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "22181:2181"
  kafka:
    image: bitnami/kafka:3.2.3
    depends_on:
      - zookeeper
    container_name: kafka
    ports:
      - '29092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "Raw:1:1,Done:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
  log-agent:
    image: log-agent:latest
    build:
      context: ./
      dockerfile: log-agent.Dockerfile
    depends_on:
      - zookeeper
      - kafka
      - log-transfer
    container_name: log-agent
  log-transfer:
    image: log-transfer:latest
    build:
      context: ./
      dockerfile: log-transfer.Dockerfile
    depends_on:
      - zookeeper
      - kafka
    container_name: log-transfer